// Copyright (c) 2023 Cisco Systems, Inc. and its affiliates
// All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package cluster

import (
	"context"
	"time"

	"github.com/app-net-interface/kubernetes-discovery/cluster/token"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

type Status int32

const (
	Creating Status = iota
	Active
	Stopping
	Inactive
	Updating
	Deleted
	Other
)

type Platform int32

const (
	UNSPECIFIED Platform = iota
	GKE
	EKS
	AKS
)

type Cluster struct {
	Name              string
	ID                string
	EndpointAddress   string
	CaCertificateData string
	Platform          Platform
	Location          string
	CreatedAt         time.Time
	Status            Status
	StatusOther       *string
	OriginalObject    interface{}
}

// DiscoveredCluster contains data and functions to either retrieve the data
// of a cluster or to authenticate and interact with that cluster.
type DiscoveredCluster interface {
	// GetData returns the data of the cluster formatted as a `Cluster` struct.
	// The original object can also be retrieved from it. Check `Cluster`
	// documentation for more.
	GetData() (*Cluster, error)
	// GetToken will ask the cloud provider to generate a token that can be
	// used to authenticate to the cluster.
	GetToken(context.Context) (*token.Token, error)
	// GetConfig will make use of `GetToken` alongside with the cluster data
	// to generate a config that can be used to generate a client for the
	// cluster or a manager for controller-runtime package.
	//
	// Please bear in mind that this config is tied to the token generated by
	// the cloud provider an may not live for long.
	GetConfig(context.Context) (*rest.Config, error)
	// GetClientset will return a Kubernetes client set that you can use to
	// perform operations on the cluster.
	//
	// Please bear in mind that this config is tied to the token generated by
	// the cloud provider an may not live for long.
	GetClientset(context.Context) (*kubernetes.Clientset, error)
}
